world: world
message: "@t님이 @k님에게 죽었습니다"
actionbar: "KILLS: @k | DEATHS: @d | COINS: @c"

pit-tp: true
pit-tp-location: 0 10 0

kits:
  default:
    armor:
      - ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: IRON_BOOTS
      - ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: IRON_LEGGINGS
      - ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: IRON_CHESTPLATE
      - ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: IRON_HELMET
    storage:
      - ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: IRON_SWORD
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
      - null
