name: Pit
version: '${version}'
main: xyz.kellsthepenguin.pit.Pit
api-version: 1.17

commands:
  pit:
    description: join to pit
  kitcreate:
    description: create kit

permissions:
  pit.commands.kitcreate:
    description: create kit
